#include<iostream>
using namespace std;
int Group()
{
	int grp;
	cout<<"Enter the group name";
	cin>>grp;
	if(grp==1)
	{
		cout<<"\t\t\tGroup-"<<grp;
		cout<<"1)Lithium(Li)\n2)Sodium(Na)\n3)Potassium(K)\n4)Rubidium(R)5)Caesium(Cs)6)Francium(Fr)";
	}
	if(grp==2)
	{
		cout<<"\t\t\tGroup-"<<grp;
		cout<<"1)Beryllium(Be)\n2)Magnesium(Mg)3)Calcium(Ca)4)Strontium(Sr)\n5)Barium(Ba)6)Radium(Ra)";
	}
	if(grp==3)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Scandium(Sc)\n2)Yttrium(Y)\n3)Lanthanum(La*)\n4)Actinium(Ac**)";
	}
	if(grp==4)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Titanium(Ti)\n2)Zirconium(Zr)\n3)Hafnium(Hf)\n4)Rutherfordium(Rf)";
	}
	if(grp==5)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Vanadium(V)\n2)Niobium(Nb)\n3)Tantalum(Ta)\n4)Dubnium(Db)";
	}
	if(grp==6)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Chromium(Cr)n\2)Molybdenum\n3)Tungsten(W)\n4)Seaborgium(Sg)";
	}
	if(grp==7)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Manganese(Mn)\n2)Technetium(Tc)\n3)Rhenium(Re)\n4)Bohrium(Bh)";
	}
	if(grp==8)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Iron(Fe)\n2)Ruthenium(Ru)\n3)Osmium(Os)\n4)Hassium(Hs)";
	}
	if(grp==9)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Cobalt(Co)\n2)Rhodium(Rh)\n3)Iridium(Ir)\n4)Meitnerium(Mt)";
	}
	if(grp==10)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Nickel(Ni)\n2)Palladium(Pd)\n3)Platinum(Pt)\n4)Darmstadtium(Ds)";
	}
	if(grp==11)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Copper(Cu)\n2)Silver(Ag)\n3)Gold(Au)\n4)(Rg)";
	}
	if(grp==12)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Zinc(Zn)\n2)Cadmium(Cd)\n3)Mercury(Hg)\n4)Copernicium(Cn)";
	}
	if(grp==13)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Boron(B)\n2)Aluminium(Al)\n3)Gallium(Ga)\n4)Indium(In)\n5)Thallium(Tl)\n6)Nihonium(Nh)";
	}
	if(grp==14)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Carbon\n2)Silicon\n3)Germanium(Ge)\n4)Tin(Sn)\n5)Lead(Pb)\n6)Flerovium(Fl)";
	}
	if(grp==15)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Nitrogen(N)\n2)Phosphorus(P)\n3)Arsenic(Ar)\n4)Antimony(Sb)\n5)Biamuth(Bi)\n6)Moscovium(Mc)";
	}
	if(grp==16)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Oxygen(O)\n2)Sulphur(S)\n3)Selenium(Se)\n4)Tellurium(Te)\n6)Livermorium(Lv))";
	}
	if(grp==17)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Florine(F)\n2)Chlorine(Cl)\n3)Bromine(Br)\n4)Iodine(I)\n5)Astatine(At)\n6)Tennessine(Ts)";
	}
	if(grp==18)
	{
		cout<<"Group-"<<grp;
		cout<<"1)Helium(He)\n2)Neon(Ne)\n3)Argon(Ar)\n4)Krypton(Kr)\n5)Xenon(Xe)\n6)Radon(Rn)\n7)Oganesson";
	}
}
